[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
#solc = "0.8.13"
ffi = true
fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/324422b5714843da8a919967a9c652ac"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
